name: CI/CD Pipeline TechStore con AWS ECR y ECS Fargate

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: techstore-cluster
  ECS_SERVICE: techstore-api-service
  ECS_TASK_DEFINITION: .aws/task-definition.json
  CONTAINER_NAME: techstore-api
  ECR_REPOSITORY: techstore-api

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar código
      uses: actions/checkout@v4
    - name: Configurar Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Permisos y Build
      run: |
        chmod +x mvnw
        ./mvnw clean package -DskipTests

  deploy-to-ecr:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Descargar código
      uses: actions/checkout@v4
    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Construir y subir imagen a ECR
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin 989804099124.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
        docker build -t ${{ env.ECR_REPOSITORY }} .
        docker tag ${{ env.ECR_REPOSITORY }}:latest 989804099124.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
        docker tag ${{ env.ECR_REPOSITORY }}:latest 989804099124.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
        docker push 989804099124.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
        docker push 989804099124.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

  deploy-to-ecs:
    needs: deploy-to-ecr
    runs-on: ubuntu-latest
    steps:
    - name: Descargar código
      uses: actions/checkout@v4
    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Renderizar Task Definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: 989804099124.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
    - name: Desplegar en ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true